# Generated by Django 2.0 on 2022-02-23 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artname', models.CharField(max_length=128)),
                ('artbirth', models.DateField()),
                ('artimage', models.ImageField(upload_to='media')),
                ('artex', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artistname', models.CharField(max_length=20)),
                ('fromm', models.CharField(max_length=128)),
                ('artistex', models.CharField(max_length=500)),
                ('artistimage', models.FileField(upload_to='media')),
                ('video', models.FileField(blank=True, null=True, upload_to='media')),
                ('link', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='art',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='box.Artist'),
        ),
    ]
