# Generated by Django 2.0 on 2022-02-23 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='artist',
        ),
        migrations.AddField(
            model_name='artist',
            name='myart',
            field=models.ManyToManyField(blank=True, to='box.Art'),
        ),
    ]
